### ISSUE TITLE
Latest build raises timeout on Cover (v1.1.2.1)

### ISSUE THREAD

**Issue by firecodergithub** [axodox/AxoTools#100]
Running tests works fine and fast, however when running cover there is SerializableException: Service creation timed out
Either the 10 secs timeout is too low (cover was running slow also in the previous version, but it was running) or there is another type of error

**Comment by axodox** [comment]
That is weird, I only improved the error reporting itself, so it does show better error message, as it was showing an empty one before in these cases. However I have found a weird, undocumented NullReferenceException thrown by .Net framework code, which I fixed just now. I have also increased the timeout to 20 seconds. I suggest to check the windows Event log, maybe AxoCover.Runner is crashing somehow.

**Comment by firecodergithub** [comment]
retested and now on v1.1.2.2 (and with VS update of today) it works correctly.
many thanks!
