### ISSUE TITLE
Build the source code in VS2017

### ISSUE THREAD

**Issue by lextm** [axodox/AxoTools#102]
The readme file lacks of certain information on how to build and debug the code. If you do use Visual Studio 2017 to build the source code, you have to ensure C# and C++/CLI are enabled. You need to install VS2012 as well, such as https://chocolatey.org/packages/VisualStudio2012WDX .

**Comment by maosierra** [comment]
And download Win 8.1 SDK, what is the wrong with? do you want to document the project?

**Comment by lextm** [comment]
@maosierra Windows 8.1 SDK has nothing to do with this project based on my investigation.

I summarized what I learned in a pull request #104 . Once that's merged, this issue can be closed.

**Comment by axodox** [comment]
Merged the PR. Thanks.
