### ISSUE TITLE
Settings per solution

### ISSUE THREAD

**Issue by axodox** [axodox/AxoTools#11]
### Message from LEBSON Mike sent on 2017-03-10 20:01:24 UTC###

> Hello,
> 
> Firstly I just want to say that AxoCover is great. We have been using OpenCover.UI up to this point and AxoCover blows it out of the water.
> 
> I have a couple suggestions related to the settings which are currently holding me back from suggesting this to the rest of my team.
> 
> 
> 1.       Allow them to be set per-solution
> 
> a.       Ideally saved in a file that can be checked in to source control. OpenCover.UI does this by creating an OpenCover.UI.Config inside an OpenCover folder in the solution folder
> 
> 2.       Add "mergebyhash" setting
> 
> 3.       Add "skipautoprops" setting
> 
> 4.       Possibly add setting to switch to line background as a method of highlighting the coverage
> 
> a.       This is just a matter of preference but I can easily get used to the way you have it now
> 
> Thanks,
> Mike Lebson
> Developer of Data Applications
> Thales InFlyt Experience

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/465309/feedback/754548](https://rink.hockeyapp.net/manage/apps/465309/feedback/754548)

**Comment by Malivil** [comment]
^ That's me. I didn't realize the feedback would go here or I would have just added the issue myself =)

**Comment by axodox** [comment]
Yes, I was thinking on disabling the synchronization of feedback until I add a notice to the UI that it will get here.

About the settings per solution, and the new opencover settings to add it is in-line with what I envisioned to be next and it will be done soon. Currently I am working on a large under the hood change, which will bring xUnit and NUnit support (and later .Net Core), as well as ability to run tests without coverage (but much faster) and performance improvements. I will try to get that out by the end of next week. This change will be done soon after that.

I will likely add the highlight line background option a little later. I plan some other improvements to the editor experience so it will be done together with that.

**Comment by axodox** [comment]
Feedback hook removed, now feedback will remain private.

**Comment by Malivil** [comment]
Awesome! Thanks for the quick reply =)

**Comment by axodox** [comment]
I decided to add the per solution settings to 1.1, so you will have it sooner :). In fact most of the stuff is already done: I have added the per solution setting support, the mergebyhash (was enabled before), and the skipautoprops (was disabled). I have not implemented the highlighting yet, but as I said that might come a little later.

You can check it in the [latest xNUnitSupport releases](https://github.com/axodox/AxoTools/releases). - These releases are not stable yet, so you will likely encounter some problems.

**Comment by Malivil** [comment]
You are awesome. I will definitely try it out tomorrow when I get to work. Thanks so much!

**Comment by Malivil** [comment]
I used it all day today with various projects in VS 2015 using MSTest and everything is working great.

I will roll this out to my team when a stable release comes out but I'm going to keep using the version I have because it works so well.

Thanks again

**Comment by axodox** [comment]
Released to marketplace
