### ISSUE TITLE
Found no unit tests when targeting x64

### ISSUE THREAD

**Issue by dlkay0** [axodox/AxoTools#110]
AxoCover v1.1.246.0 reports no unit tests found when Platform target is x64.  Tests appear when Platform target is Any CPU.

**Comment by axodox** [comment]
Please go to AxoCover settings and select the x64 as test platform at the bottom.

**Comment by dlkay0** [comment]
Thanks for the quick response.  That resolved my issue.  Didn't realize the setting was there.
