### ISSUE TITLE
Not enough contrast between the white Visual Studio caret and the light teal axoCover was-covered markers

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoTools#112]
I'm seeing not enough contrast between the white Visual Studio caret and the light teal axoCover was-covered markers:

![image](https://user-images.githubusercontent.com/1912242/29672316-8196e476-88b1-11e7-8234-fd43e0a6930e.png)

**Comment by axodox** [comment]
You can change the color in settings. I will consider changing the default too.

**Comment by NeilJustice** [comment]
Thanks for that setting!

**Comment by axodox** [comment]
Fix released.
