### ISSUE TITLE
runSettings file is not shown in AxoCover

### ISSUE THREAD

**Issue by Steinblock** [axodox/AxoTools#113]
In the root of my project I have a file `default.runsettings`

```
<?xml version="1.0" encoding="utf-8"?>  
<RunSettings>  
  <!-- Configurations that affect the Test Framework -->  
  <RunConfiguration>  
    <MaxCpuCount>52</MaxCpuCount>  
  </RunConfiguration>  
</RunSettings>  
```

But I cannot select this file in AxoCover `1.1.2.10` because the list is empty.

![image](https://user-images.githubusercontent.com/6850324/29958499-5c4cd480-8ef3-11e7-9654-fe5171670879.png)

**Comment by Malivil** [comment]
At first glance I might assume the extension is case sensitive. Try renaming the file to default.runSettings (with the S instead of s) and see if that makes a difference.

**Comment by Steinblock** [comment]
I figured it out: The file was present in file system but not part of the solution. After `Solution -> Add -> Existing Item` axoCover detected the file. 

Anyway the file shows as `C:\Users\juergen\Source\Repos\solution\default.runSettings` and even get's persisted as `"TestSettings": "C:\\Users\\juergen\\Source\\Repos\\solution\\default.runSettings",` in settings.json instead of the relative file location, which isn't very source control friendly :-)

**Comment by axodox** [comment]
Ok, I will remove the absolute path

**Comment by Steinblock** [comment]
I created a new issue for that #115 so I can close this one.
