### ISSUE TITLE
axocover should not automatically update settings.json

### ISSUE THREAD

**Issue by Steinblock** [axodox/AxoTools#116]
I have the following issue:

* I am on my master branch

This is how my settings.json file looks

```
{
  "TestRunner": "",
  "TestPlatform": "x86",
  "TestApartmentState": "STA",
  "TestAdapterMode": "Integrated",
  "IsRedirectingFrameworkAssemblies": true,
   ...
}
```

* I switch to an old topic branch where the settings file looks different (i.e. IsRedirectingFrameworkAssemblies) is missing.

```
{
  "TestRunner": "",
  "TestPlatform": "x86",
  "TestApartmentState": "STA",
  "TestAdapterMode": "Integrated",
   ...
}
```

Now the file is instantly under pending changes because axocover added the new setting. Trying to switch to another branch fails because `settings.json` has been modified.

I think axocover should only persist changes into settings.json after making a change to settings tab.

**Comment by axodox** [comment]
You are right! There was a mistake in the implementation. Now I fixed it, so it should work properly.
