### ISSUE TITLE
Is it posible to run AxoTools coverage under VSTS CI?

### ISSUE THREAD

**Issue by comdiv** [axodox/AxoTools#118]

**Comment by lextm** [comment]
AxoTools is just the Visual Studio extension. If you want to get unit test coverage under VSTS, you need to use other tools, such as https://github.com/RobertK66/vsts-opencover. Generally speaking, the trick is to call OpenCover command line and parse its coverage report.

**Comment by axodox** [comment]
I can add that after running your tests from command line through OpenCover, you can use ReportGenerator to generate a HTML report. So you have a fine coverage report at the end of your CI build.

**Comment by comdiv** [comment]
Thx

**Comment by axodox** [comment]
Question answered, time to close issue.
