### ISSUE TITLE
Coverage report browser launch stops working when the user clicks Export, then closes the "Report generator" dialog, then clicks Export again

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoTools#119]
Automatic launching of the default browser to display a coverage report stops working when the user clicks Export, then closes the "Report generator" dialog while the report is still generating, then clicks Export again.

Step 1: Run tests with coverage then click Export.

![image](https://user-images.githubusercontent.com/1912242/30330843-c8cdfb7e-979b-11e7-9806-7f85ea3764a4.png)

Step 2: Click the X or press Alt+F4 in the brief window of time during which the coverage report is generating.

![image](https://user-images.githubusercontent.com/1912242/30330854-cd699c1a-979b-11e7-8967-a992a84b60e5.png)

Step 3: Click Export again.

![image](https://user-images.githubusercontent.com/1912242/30330843-c8cdfb7e-979b-11e7-9806-7f85ea3764a4.png)

Step 4: Note that the default browser no longer automatically launches to display the coverage report, and that clicking OK does not launch the coverage report.

![image](https://user-images.githubusercontent.com/1912242/30330865-d1f94050-979b-11e7-9417-24620cff5152.png)

**Comment by axodox** [comment]
Released this last week, forgot to close.
