### ISSUE TITLE
AxoCover does not detect Visual Studio 2017 (aka MSTest V2) Test projects

### ISSUE THREAD

**Issue by Steinblock** [axodox/AxoTools#12]
While AxoCover does detect unit tests for my existing (pre Visual Studio 2017) projects, it does not seem to work with [MSTest V2](https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/17/taking-the-mstest-framework-forward-with-mstest-v2/)

Here are the steps to reproduce

* Create a new project with visual studio 2017
* Create a new test project with visual studio 2017 (or just reference `MSTest.TestAdapter` and `MSTest.TestFramework` within any project)
* While MSTest Window automatically detects the unit tests, AxoCover does not.

![axocover](https://cloud.githubusercontent.com/assets/6850324/23889196/11556d04-088c-11e7-973f-ce961459ad7c.PNG)

Happens even with 1.0.70 installed, it looks like 9f1e9a0c9e4cb918c4632ba271ce2c16f67e46da should address this but it doesn't.

**Comment by axodox** [comment]
Thanks for the report, I will investigate it tomorrow.

**Comment by axodox** [comment]
That is weird, it is working for me:
![image](https://cloud.githubusercontent.com/assets/22882208/23954392/698b740a-0954-11e7-8cc7-4b990e8a13d3.png)
Can you please verify that you have the latest version?

**Comment by Steinblock** [comment]
That is really weird, 

I basically just did the same:

* Create a new project with visual studio 2017
* Create a new test project with visual studio 2017

and it works out of the box while my `ConsoleApp1` still doesn't. I really can't tell why.
Even a diff of the project files shows nothing different.
