### ISSUE TITLE
1.1.2.10 or 1.1.250

### ISSUE THREAD

**Issue by andrelundin** [axodox/AxoTools#120]
When I download the latest release (or also if I do it via Visual Studio Marketplace) it tells me I have installed 1.1.2.10 even though latest release here says 1.1.250

Am I doing something wrong?

**Comment by axodox** [comment]
No, the 1.1.2.10 is the "marketing" version (for tracking features in changelog), while 1.1.250 is the build version (assigned by the build server). Both are displayed in the settings view. I had a plan to merge the two, but I decided to put it on hold for now as it would require to generate the changelog and I decided that in the amount of free time I have I focus the other issues instead.

**Comment by andrelundin** [comment]
Ah. Ok. Thank you for the clarification
