### ISSUE TITLE
SerializableException when trying to do Run or Cover

### ISSUE THREAD

**Issue by mikeachten** [axodox/AxoTools#123]
When I try to do a Run or Cover command on my solution, AxoCover throws an serializeableException, , explaining that it has no access to the directory .axoCover.

.axoCover is readonly (I cannot change this) and I've given 'Everyone' full access to this directory. But it still throws this exception.

Last week AxoCover was still working in the same solution. I have had no windows updates or anything like that in the past week.

Output from AxoCover:
> Executing tests...
| Runner version is 1.1.262.0.
| We are on x86 platform.
| Using run settings  C:\Projects\eBoekhouden.nl V2\Main\.axoCover.
< Could not execute tests.
< SerializableException: Toegang tot het pad C:\Projects\eBoekhouden.nl V2\Main\.axoCover is geweigerd.
<    bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
<    bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
<    bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
<    bij System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
<    bij System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
<    bij System.IO.File.ReadAllText(String path)
<    bij AxoCover.Runner.TestExecutionContext..ctor(ITestExecutionMonitor monitor, TestExecutionOptions options) in C:\projects\axotools\AxoCover.Runner\TestExecutionContext.cs:regel 91
<    bij AxoCover.Runner.TestExecutionService.RunTestsWorker(TestExecutionTask[] executionTasks, TestExecutionOptions options) in C:\projects\axotools\AxoCover.Runner\TestExecutionService.cs:regel 109
Shutting down...
Exiting...
Test execution finished.`

**Comment by axodox** [comment]
Sorry for that, I have updated how settings are saved, and it seems it broke the runner in certain cases. Should work properly now.
