### ISSUE TITLE
NUnit support

### ISSUE THREAD

**Issue by axodox** [axodox/AxoTools#15]

**Comment by tomkuijsten** [comment]
Would be fantastic to have nunit support! I'm using it for the first time and looks promising, but nunit is our standard test framework.

**Comment by axodox** [comment]
You can try one of the xNUnitSupport AxoCover builds from here: https://github.com/axodox/AxoTools/releases. These are already supporting NUnit, should be released on the VS marketplace soon too.

**Comment by tomkuijsten** [comment]
Thanks!

**Comment by pavzaj** [comment]
Nice job. Opencover at last usable in IDE thanks to you:)

**Comment by ivancitin** [comment]
Initially posted on the visual studio marketplace page, but figure it will be better here. This is to report NUnit tests not being discovered.

Hello,

I'm just giving this a first try, it's something that could be really helpful. I'm trying the pre-release 1.1.94.0 for NUnit support.

It wasn't initially working so I decided to create an empty project and incorporate tests one by one, for my surprise it worked for the first two test classes and stopped working when added the third one.

I then was able to verify that by adding a simple class with a super class it stopped discovering the test, something as simple as:

namespace ABC
{
    class A : B
    {
        public A() { }
    }
}

where class B is on a different project (referenced on the test project). Just remove the super class from class A and test gets discovered again.

**Comment by ivancitin** [comment]
Enums on a test class will prevent the tests from being discovered, example:

<pre>
[TestFixture]
public class TestClass
{
	// Just adding this prevent test from being discovered
	static readonly EnumAbc V = EnumAbc.Value1;
	
	[SetUp]
	public void setup()
	{	
	}

	[Test]
	public void SomeTest()
	{
	}
}
</pre>

**Comment by axodox** [comment]
I cannot reproduce this. What about this enum, is it coming from another assembly?

**Comment by axodox** [comment]
The base class issue is caused by the nunit vs test adapter used in AxoCover. As I see the last pull request they merged fixes the issue.

**Comment by axodox** [comment]
Please check if using latest nunit3 test adapter the same happens in test explorer.
If that is the case please raise issue there.

**Comment by ivancitin** [comment]
I have NUnit 3 TestAdapter version 3.7.0 (latest) and the test explorer does discover the test, but not AxoCover, if there is a class with a base class on the test project, like the example above.

For the enum case, yes, the enum is on separate assembly.

**Comment by axodox** [comment]
I have created a fix on branch bugfix/issue15, please go to settings/releases & updates, check for updates (refresh), then change your branch and press update. After restart your test should work, note: it turned out we need to update to the latest nunit framework package for the fix to work in the project too.

**Comment by ivancitin** [comment]
Hi!

I really appreciate your support and the work you guys are doing. Unfortunately the update didn't solve the problem on my end. Maybe there is something else going on with the NUnit Adapter.

If I including on the test project a class with a base class on a separate project no tests is discovered, moved that class out of the test project to a third project and tests gets discovered, in both cases test shows on the test explorer.

**Comment by axodox** [comment]
I could reproduce your issue and the fix provided solved it for me. Maybe you need to update the NUnit on your projects, it only works for me if you have 3.6.1+ for me.

**Comment by axodox** [comment]
Released to marketplace
