### ISSUE TITLE
Cannot discover tests in Visual Studio 2017

### ISSUE THREAD

**Issue by Galad** [axodox/AxoTools#27]
Hello,
An error is occuring when discovering NUnit tests. Test assemblies are properly listed but there is no tests inside. Here is the error from the output window :

    Test discovery started.
    INFO Loading assembly from C:\Users\galad\AppData\Local\Microsoft\VisualStudio\15.0_e8097cf3\Extensions\bkrxpd31.3ry\NUnitAdapter\NUnit3.TestAdapter.dll...
    INFO Assembly loaded.
    INFO Loading assembly from C:\Users\galad\AppData\Local\Microsoft\VisualStudio\15.0_e8097cf3\Extensions\bkrxpd31.3ry\xUnitAdapter\xunit.runner.visualstudio.testadapter.dll...
    INFO Assembly loaded.
    INFO Loading assembly from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.dll...
    FAIL Could not load assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.dll.
    FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.
       à System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
       à System.Reflection.RuntimeAssembly.GetExportedTypes()
       à AxoCover.Common.Extensions.GenericExtensions.FindImplementers[T](Assembly assembly) dans C:\projects\axotools\AxoCover.Common\Extensions\GenericExtensions.cs:ligne 18
       à AxoCover.Runner.TestDiscoveryService.LoadDiscoverers(String adapterSource) dans C:\projects\axotools\AxoCover.Runner\TestDiscoveryService.cs:ligne 48
    
    
    INFO Discovering tests...
    INFO Running discoverer: NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer...
    INFO NUnit Adapter 3.7.0.0: Test discovery starting
    Test execution failed.
    Exception: Test discovery timed out.
       at AxoCover.Models.TestProvider.<>c__DisplayClass11_0.<GetTestSolutionAsync>b__0() in C:\projects\axotools\AxoCover\Models\TestProvider.cs:line 82

Using :
Visual Studio 2017 Professional
AxoCover xNUnitSupport-1.1.44

**Comment by axodox** [comment]
Please use latest xNUnitSupport release for a fix.
