### ISSUE TITLE
AxoCover assemblies included in coverage report

### ISSUE THREAD

**Issue by Malivil** [axodox/AxoTools#29]
Running pre-release 1.1.0.46 (build 1.1.49) on Visual Studio 2015 Professional, 3 AxoCover assemblies are showing in the  coverage report

![image](https://cloud.githubusercontent.com/assets/1238511/24409953/b737a566-139f-11e7-9be5-69adab557847.png)

I was running build 1.1.31 before this and I don't remember seeing this issue with that build.

**Comment by axodox** [comment]
Fixed in: https://github.com/axodox/AxoTools/releases/tag/xNUnitSupport-1.1.54

**Comment by Malivil** [comment]
Verified. Thanks for the quick fix!
