### ISSUE TITLE
MS Tests were not loaded while using VS 2017

### ISSUE THREAD

**Issue by kabilanvk** [axodox/AxoTools#41]
I tried building the whole solution but no tests were found. The environment details are following,
IDE: VS 2017 v15.1(26403.7)
Project Framework: 4.5.2
AxoCover version: 1.1.0.55
Build: bugfix/issue36 1.1.94.0

Logs:
Test discovery started.
INFO Loading assembly from C:\Users\Kabilan\AppData\Local\Microsoft\VisualStudio\15.0_dcc1b7d5\Extensions\4ju00mp3.fi1\MSTestAdapter\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from C:\Users\Kabilan\AppData\Local\Microsoft\VisualStudio\15.0_dcc1b7d5\Extensions\4ju00mp3.fi1\NUnitAdapter\NUnit3.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from C:\Users\Kabilan\AppData\Local\Microsoft\VisualStudio\15.0_dcc1b7d5\Extensions\4ju00mp3.fi1\xUnitAdapter\xunit.runner.visualstudio.testadapter.dll...
INFO Assembly loaded.
INFO Discovering tests...
INFO Running discoverer: Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestDiscoverer...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Apis.Test\bin\Debug\CloudConnect.Apis.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Common.Test\bin\Debug\CloudConnect.Common.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Configuration.Test\bin\Debug\CloudConnect.Configuration.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Core.Test\bin\Debug\CloudConnect.Core.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NMS.Test\bin\Debug\CloudConnect.NMS.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NMSPartner.Test\bin\Debug\CloudConnect.NMSPartner.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NortonFamily.Test\bin\Debug\CloudConnect.NortonFamily.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Onboard.Test\bin\Debug\CloudConnect.Onboard.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Rover.Test\bin\Debug\CloudConnect.Rover.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.ServiceProvider.Test\bin\Debug\CloudConnect.ServiceProvider.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.UnitTest.Core\bin\Debug\CloudConnect.UnitTest.Core.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\Integration.Test\bin\Debug\Integration.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\Norton.Integration.Test.Framework\bin\Debug\Norton.Integration.Test.Framework.dll...
INFO Discoverer finished.
INFO Running discoverer: NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Apis.Test\bin\Debug\CloudConnect.Apis.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.Apis.Test\bin\Debug\CloudConnect.Apis.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Common.Test\bin\Debug\CloudConnect.Common.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.Common.Test\bin\Debug\CloudConnect.Common.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Configuration.Test\bin\Debug\CloudConnect.Configuration.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.Configuration.Test\bin\Debug\CloudConnect.Configuration.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Core.Test\bin\Debug\CloudConnect.Core.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.Core.Test\bin\Debug\CloudConnect.Core.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NMS.Test\bin\Debug\CloudConnect.NMS.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.NMS.Test\bin\Debug\CloudConnect.NMS.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NMSPartner.Test\bin\Debug\CloudConnect.NMSPartner.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.NMSPartner.Test\bin\Debug\CloudConnect.NMSPartner.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NortonFamily.Test\bin\Debug\CloudConnect.NortonFamily.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.NortonFamily.Test\bin\Debug\CloudConnect.NortonFamily.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Onboard.Test\bin\Debug\CloudConnect.Onboard.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.Onboard.Test\bin\Debug\CloudConnect.Onboard.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Rover.Test\bin\Debug\CloudConnect.Rover.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.Rover.Test\bin\Debug\CloudConnect.Rover.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.ServiceProvider.Test\bin\Debug\CloudConnect.ServiceProvider.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.ServiceProvider.Test\bin\Debug\CloudConnect.ServiceProvider.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.UnitTest.Core\bin\Debug\CloudConnect.UnitTest.Core.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\CloudConnect.UnitTest.Core\bin\Debug\CloudConnect.UnitTest.Core.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\Integration.Test\bin\Debug\Integration.Test.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\Integration.Test\bin\Debug\Integration.Test.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Checking C:\Working\P4_CCV3_Test\src\Norton.Integration.Test.Framework\bin\Debug\Norton.Integration.Test.Framework.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
INFO Assembly contains no NUnit 3.0 tests: C:\Working\P4_CCV3_Test\src\Norton.Integration.Test.Framework\bin\Debug\Norton.Integration.Test.Framework.dll
INFO NUnit Adapter 3.7.0.0: Test discovery complete
INFO Discoverer finished.
INFO Running discoverer: Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Apis.Test\bin\Debug\CloudConnect.Apis.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Common.Test\bin\Debug\CloudConnect.Common.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Configuration.Test\bin\Debug\CloudConnect.Configuration.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Core.Test\bin\Debug\CloudConnect.Core.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NMS.Test\bin\Debug\CloudConnect.NMS.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NMSPartner.Test\bin\Debug\CloudConnect.NMSPartner.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.NortonFamily.Test\bin\Debug\CloudConnect.NortonFamily.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Onboard.Test\bin\Debug\CloudConnect.Onboard.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.Rover.Test\bin\Debug\CloudConnect.Rover.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.ServiceProvider.Test\bin\Debug\CloudConnect.ServiceProvider.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\CloudConnect.UnitTest.Core\bin\Debug\CloudConnect.UnitTest.Core.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\Integration.Test\bin\Debug\Integration.Test.dll...
INFO Checking C:\Working\P4_CCV3_Test\src\Norton.Integration.Test.Framework\bin\Debug\Norton.Integration.Test.Framework.dll...
INFO Discoverer finished.
Test discovery finished.
INFO Test discovery finished.

**Comment by axodox** [comment]
Is this MSTestV1 or V2?
For MSTestV1 you might need to go to settings and select "Integrated" test adapter mode.
For MSTestV2 you should use 1.1.14 for now, the 1.1.17 seem to break compatibility.

**Comment by kabilanvk** [comment]
Thanks for the immediate response. 
I'm using MSTestV1 and it works now when i switched to "Integrated" test adapter mode.

**Comment by Flohack74** [comment]
I had the same problem, does anyone know how I can convert V1 to V2, since we are also using NUnit and I need to see both types.
