### ISSUE TITLE
Line coverage fails for closing brace in tests expecting exceptions

### ISSUE THREAD

**Issue by nelsonhf** [axodox/AxoTools#53]
For a test like:
```
[TestMethod]
[ExpectedException(typeof(Exception))]
public void SomeTest()
{
   ThrowsException();
} // Coverage fails for this line
```
AxoCover will show that the closing brace is not covered (as the comment shows).

Although it is technically correct (the line will never be reached for any successful test), I would like to, at least, be able to indicate that coverage for this line should be ignored as I am targeting a 100% coverage.

**Comment by axodox** [comment]
To be honest I agree with the current result, but for sure you should report this on the [OpenCover](https://github.com/OpenCover/opencover) project's issue board as AxoCover displays OpenCover results.

Also some testing tips:
- You should check the coverage of the application under test, not your test code. The coverage of the tests by themselves is not really relevant in most cases - well if you really have much test code which never runs, then you might need to refactor something.
- Generally you should not aim to have 100% coverage as in most cases that has marginal benefit over let's say 70% or 85% coverage.
- It is more important to make your tests are really doing their job, e.g. if you change what your code does in a significant way, they fail - so you be sure they prevent regressions. See [mutation testing](https://en.wikipedia.org/wiki/Mutation_testing).

**Comment by nelsonhf** [comment]
I am not really sure if I agree or not with the result. I dislike not getting
100%, though (I am THAT competitive and perfectionist…).
On the other hand, I completely agree with you that the code is what matters and
coverage in the tests is good to know (but why would someone add conditionals to
a unit test is beyond me!) but not very relevant.
Mutation test is something that I do a lot when I am not TDD-ing, just to make
sure that my tests are meaningful. I liked that what I do has a proper name!
Thanks for the prompt response and, especially, for the program!  





On Sun, Apr 30, 2017 12:39 AM, Péter Major notifications@github.com  wrote:
Closed #53.

**Comment by sawilde** [comment]
Of course the callee function may not actually throw an exception and as such there is a sequence point after the function has returned

**Comment by fernando-t1073** [comment]
You may use like this:

[TestMethod]
public void SomeTest()
{
   Assert.ThrowsException<Exception>(() => ThrowsException());
} // Coverage will work in this line

**Comment by sawilde** [comment]
Ah well - it seems the sequence point for the line also encapsulates the end brace
