### ISSUE TITLE
NUnit2 Support

### ISSUE THREAD

**Issue by ljchristinson** [axodox/AxoTools#77]
Would it be possible to add support for NUnit2? Looks like NUnit 3 is supported but not the older version. I know NUnit3 should be used over 2 at this point, but one of the projects I work on is a legacy project and changing the NUnit version will probably never happen. 

It would be great to be able to use AxoTools!

**Comment by Buttonsz** [comment]
I played around with this a little this morning. As a quick fix to get it to work I did the following:

1. Got the master branch from Github
2. Added the dll's from the NUnit (Version 2.6.3, Runtime 2.0) extension folder to the NUnitAdapter folder in the AxoCover extension folder (Or to the dependencies project).
3. Checked the "RunTests" method through DotPeek for the NUnit.VisualStudio.TestAdapter.dll and found it calls a context method called "set_EnableShutdownAfterTestRun". 
4. Went into the AxoCover.Runner project and altered the TestExecutionContext property called EnableShutdownAfterTestRun and removed the throw NotSupportedException(); from the set
5. Built the changed solution and ran the installer

I'd need to look further into what the set is actually meant to be doing, but for now the tests are discovered in the AxoCover extension within VS2017 and I can also run tests and coverage on them fine.

I'm sure axodox probably has a better solution but for now hope this helps a little if you need coverage quickly.

**Comment by axodox** [comment]
Hi, I just wanted to say that it is likely to be very quick to do it, but now it is confirmed :)

What I would do is basically the same:
- Fork repo
- Create a branch feature/nunit2support
- Add an NUnitAdapter2 folder (and rename the other to NUnitAdapter3) and bring in the needed dlls from nuget
- Fix the mentioned EnableShutdownAfterTestRun method, we can ignore the request I think, nothing used it so far, so I left it like that for testing purpose
- Test it on some larger projects and validate if it works OK, if not please investigate - in case of NUnitV3 I forked the VS test adapter for NUnit3 and added some change, you may check my fork of the repo
- Update changelog, increase build version
- You may add your name to license, and list that you did the nunit v2 support
- Create a pull request
 Then I will take over, review, merge and release the changes.

I would do it myself, but I have to travel to Canada this weekend (I am from Hungary), so will not have much time, well maybe on the plane...

**Comment by ljchristinson** [comment]
Thanks to both of you for the quick responses. I'm willing to take a stab at it.

**Comment by Buttonsz** [comment]
No problem. And thanks axodox, I'll have chance to do what you suggested tonight with the changes.

**Comment by ljchristinson** [comment]
I added a pull request for NUnit2 support, which axodox reviewed, so I'll close this issue.

**Comment by axodox** [comment]
Changes available in: https://github.com/axodox/AxoTools/releases/tag/master-1.1.191

**Comment by axodox** [comment]
Thank you for the work!
