### ISSUE TITLE
I get the coverage only of my tests methods, not the main methods that I am testing

### ISSUE THREAD

**Issue by ComptonAlvaro** [axodox/AxoTools#79]
I have a solution with two projects, one with my main application with the methods that I want to test and other project for the tests, because I want to have one dll for the main application and other dll for the tests, because I don't want to include my test classes in the dll of the main application.

When I run the tests, I get the coverage of my test methods, but I don't get the coverage of the methods that I want to test, the methods of my main project.

So I would like to know how I could get the coverage of the main methods.

Thanks.

**Comment by axodox** [comment]
There is no requirement to include the test code in your main application, in fact I have never seen anything like that at all with .Net.
Based on your description I think you might have something configured in a way that prevents the coverage to be calculated for your main assembly. Please validate that that the appropriate PDB files are in the same directory as your assemblies under test. It is also possible that you have some old version of your DLLs/EXEs left somewhere causing the trouble. If you specified filters, or changed the default assembly filtering settings that could also exclude your code. Also make sure that your test code directly calls the code in the assembly under test (e.g. if you spawn a new process, and just communicate with it through network, it won't get the OpenCover profiler attached which is needed for coverage).

**Comment by ComptonAlvaro** [comment]
If I am not wrong, AxoTools use OpenCover, and I guess that OpenCover is not compatible with .net Standard. Is it right?

Because if it is right, the problem is that, because my main assembly is a .net standard application.

**Comment by axodox** [comment]
I guess it will have to do with the PDB format. Please ensure that you compile with full PDB (not portable).

**Comment by ComptonAlvaro** [comment]
@axodox thank you so much. Could you tell me how I could do that?

**Comment by axodox** [comment]
I haven't tried this by myself, but guys at OpenCover apparently got it working with that, so it should work with AxoCover too.

Check this thread: https://github.com/OpenCover/opencover/issues/601

**Comment by ComptonAlvaro** [comment]
In my case I have use -oldtyle parameter to run opencover manually (not with Axo Tools) but my assembly is not included. In my case I am using a .net standard assembly, not .net core, perhaps it is different.

**Comment by ComptonAlvaro** [comment]
@axodox I have found how to enable full pdbs. In VS2017, in project properties, in compile options, in the button of the page, I found the adavance options button, there I can set the PDBs to full from portable. Noe it works perfecly.

Thanks so much.

**Comment by axodox** [comment]
Happy that it works for you, I will close the issue.
