### ISSUE TITLE
Unit tests with ExpectedException attribute are marked as failed

### ISSUE THREAD

**Issue by olliaustor** [axodox/AxoTools#81]
This kind of unit test is marked as failed - even if it succeeded because a known/expected exception is thrown:

`[TestMethod]`
` [ExpectedException(typeof(NotSupportedException))]`
`  public void ThrowKnownException_IsMarkedAsFailed()`
`  {`
`       throw new NotSupportedException();`
`  }`

**Comment by axodox** [comment]
I could not reproduce the issue with MSTestV1 and V2 with latest master by copy-posting your code. What version of AxoCover are you using?

**Comment by olliaustor** [comment]
Visual Studio 2017
Installed version: AxoCover 1.0.73.7

Selected Test Runner: VsTestRunner
<img width="598" alt="axocover_vs" src="https://cloud.githubusercontent.com/assets/1780193/26624327/d72ed050-45f0-11e7-893d-4bcf90c92686.png">

Selected Test Runner: MsTestRunner
<img width="596" alt="axocover_ms" src="https://cloud.githubusercontent.com/assets/1780193/26624359/ebfd1aaa-45f0-11e7-8cb8-15adb9d42b92.png">

**Comment by axodox** [comment]
Hmm, I still fail to reproduce the issue with VS2017 and AxoCover 1.0.73.7. I tried both MsTestV1 and MsTestV2.

Can you try to rebuild the project? Or attach your failing project in a zip file.

**Comment by axodox** [comment]
This thread seems to be dead. If you still experience the issue please reopen and provide further information.
