### ISSUE TITLE
Hove: Show buttons text

### ISSUE THREAD

**Issue by wahmedswl** [axodox/AxoTools#83]
Hi, please show Button text on Hover as when pinned and its size is small, Button text is not show full and Hover also don't show the Text.

![image](https://cloud.githubusercontent.com/assets/15020561/26629649/b87c8540-461c-11e7-91a8-84765380d025.png)

Thanks

**Comment by axodox** [comment]
Sure thing, I noticed this too, I will add it to the button style.

**Comment by wahmedswl** [comment]
@axodox thank you so much 👍

**Comment by wahmedswl** [comment]
Hi, it seems like this isn't added yet, downloaded latest release and i cannot still get Tooltips.

**Comment by axodox** [comment]
This wasn't implemented yet. As I was focusing on other problems. I want to make it so it only displays when the text does not fit, as otherwise I found it distracting.

**Comment by wahmedswl** [comment]
ok, will check in next release as this is not important, just minor. Thanks for your quick feedback 👍

**Comment by axodox** [comment]
Done.
