### ISSUE TITLE
Rebuild: Individual Test

### ISSUE THREAD

**Issue by wahmedswl** [axodox/AxoTools#84]
Hi, When running individual Test while developing, it would be great if there be some option to rebuild as while changing Test and running it, it give false values due to that.

It would be great if there be some option on which when running Test, it rebuild the Test dll and then run individual test against it. Currently, it work if we Rebuild from Top and then run the individual Test.

Thanks so much for this awesome Tool 👍

**Comment by axodox** [comment]
For now I suggest to select the class you work on in the test tree, and then right click it and select cover after build, so every time you build it reruns the test

**Comment by axodox** [comment]
But otherwise I will add an option, which will make run, cover and debug rebuild the test before proceeding when needed and make it enabled on default.

**Comment by wahmedswl** [comment]
@axodox thanks for the nice suggestion. Yeah, that would be great.

Thanks
