### ISSUE TITLE
AppDomain.CurrentDomain.BaseDirectory is C:\Program Files

### ISSUE THREAD

**Issue by mhartmann2** [axodox/AxoTools#87]
If you use AppDomain.CurrentDomain.BaseDirectory in a unit test (maybe for reading some files of test data), this member is OK, when you debug a single unit test. If clicking on "Run", the property BaseDirectory contains "C:\Program Files" and all the tests fail.

**Comment by axodox** [comment]
Thanks I will look into this issue. Can you please provide the version of AxoCover you are running?

Also you may want to try the current beta version from here: https://github.com/axodox/AxoTools/releases/tag/master-1.1.191

**Comment by axodox** [comment]
I just run a quick test, and with the https://github.com/axodox/AxoTools/releases/tag/master-1.1.191 this should work properly.

**Comment by mhartmann2** [comment]
I used the latest version from Visual Studio Marketplace (mentioned as
version 1.0.73.7 there).
I will not install AxoCover any more (no release and nor beta version).

2017-06-01 15:52 GMT+02:00 Péter Major <notifications@github.com>:

**Comment by axodox** [comment]
Well, its your call.
