### ISSUE TITLE
Starting Tests not working

### ISSUE THREAD

**Issue by Naturalbornhippy** [axodox/AxoTools#93]
Hello,we have a problem in VS 2015 / Update 3 with starting Tests.
On my machine (VS 2015 / Update2) it is working without problem. The same Project is not working on my team mates computer. 

We have installed ovenCover as package and than AXOCover over Tools. After Building the project all Tests are recognized and we can see classes and stuff. If we now click tests, it seems that nothing happens.

In the status bar of AxoCover we see Testrun failed. The Log says:
Coverage executor has started.
Coverage executor has finished.

Any Idea, what this could be?

**Comment by axodox** [comment]
What version of AxoCover do you use? Is it the same version on all the computers? Note that AxoCover has a master (beta) and a release (marketplace) build, which as of now use a different runner engine. Based on the log you are on the release build, go to settings, and change the branch to master + update + restart (or use [this](https://github.com/axodox/AxoTools/releases/tag/master-1.1.193)). 
![image](https://user-images.githubusercontent.com/22882208/27412425-7b9b5276-56c2-11e7-82d8-7393b5d7f49c.png)
This might resolve your issue. (The beta is stable right now, and is expected to be merged to release branch soon.)

There is no need to add OpenCover package by the way as AxoCover extension ships with it. If the problem persists in the master version too, I suggest to check windows event log, and there in the application log you should see if there was a crash in the test runner and the type of exception / stack trace, and send that to me.

**Comment by axodox** [comment]
This thread was inactive for a long with pending questions remaining, so I decided to close it. If you still need help please don't hesitate to ask. Thanks.
