### ISSUE TITLE
Installing AxoCover causes tests to disappear?

### ISSUE THREAD

**Issue by JakenVeina** [axodox/AxoTools#98]
I've got a project with a few hundred tests in it, utilizing NUnit, but AxoCover is unable to discover any of them. Interestingly, all the tests also disappear from the default Test Explorer as well. I can rebuild and re-open the solution as many times as I want, but neither explorer displays any tests. As soon as I remove AxoCover from Visual Studio, all the tests appear again, in Test Explorer.

I created a small dummy test application, utilizing both MSTest and NUnit, and don't observe this behavior at all. Both Test Explorer and AxoCover display all the tests and run them successfully.

Both solutions target .NET Framework 4.6. The biggest difference is that for the solution where tests don't appear, the primary project is a VSIX Extension.

I'm running from the AxoCover master branch, version 1.1.211.0, within Visual Studio Community 2017.

The full solution that I'm having trouble with is linked below. You might notice, it's also effectively useless now that I've found AxoTools, which does everything I wanted to do with my project, but far better, and with a ton more features that I'd never even considered. So, kudos. :)

https://github.com/JakenVeina/BetterTestExplorer

**Comment by axodox** [comment]
I know about the issue with the missing tests, I even have the fix done, but unfortunately I am having problems building it with appveyor and had no time to fix that yet. It is in [this branch](https://github.com/axodox/AxoTools/tree/feature/dllRedirection) if you want to try it. (Note: this is unlikely to solve the problem of AxoCover not seeing the tests, but it should fix the integrated text explorer.)

**Comment by axodox** [comment]
Also I am doing this project alone so far and it already took much more time than I have anticipated. So if you would like to join you are absolutely welcome!

**Comment by axodox** [comment]
I have fixed the build and put the fix to the disappearing explorer tests on master. I tried to build your project, but a lot of dependencies related to the test platform are missing. Can you tell me where I can get those?

**Comment by JakenVeina** [comment]
There are a couple of DLL's I manually included in the projects, and everything else should be just NuGet packages.

What namespaces/classes are missing? Is it just all the Visual Studio stuff?

**Comment by axodox** [comment]
In the main project:
![image](https://user-images.githubusercontent.com/22882208/27983540-418c7f42-63bf-11e7-9312-120a949bf159.png)

In test project:
![image](https://user-images.githubusercontent.com/22882208/27983535-0c7417fc-63bf-11e7-8234-f1ff31b27fa9.png)

In the project file I see the hint paths point to the packages folder for these, but the packages.config does not have these in it so they are not downloaded.

**Comment by JakenVeina** [comment]
That's odd that so many of the VisualStudio interop is missing, especially considering those packages are all actually in "packages.config"

The TestPlatform stuff makes more sense. The published version on NuGet is quite a bit dated, so I had to grab the latest pre-release directly from GitHub.

I just went ahead and zipped up the whole solution for ya. You might still need to manually resolve some of the VisualStudio references, but you should be able to find them in the VS Install directory.

**Comment by axodox** [comment]
Where I can find the mentioned zip file?

**Comment by axodox** [comment]
Also latest release build does no longer interfere with the integrated test explorer, so the tests should not disappear anymore for you either.

**Comment by JakenVeina** [comment]
The ZIP is under "Releases" on the repo for then project, linked earlier.

**Comment by axodox** [comment]
The ZIP does not contain the DLL-s mentioned.

**Comment by JakenVeina** [comment]
Well, that baffles me, cause the only DLL's I didn't include in that package are the ones provided by the Visual Studio Extensions Dev Kit.

Regardless, I've verified that the issue is no longer present with the latest release, so feel free to go ahead and close this.

**Comment by axodox** [comment]
Thanks. Have a nice day!
